### ISSUE TITLE
Intersection processes

### ISSUE THREAD

**Issue by mmostovnikov** [ExNexu/akka-actor-locking#1]
This test shows that different processes can be executed at the same time for the same object.

```
    "process sequential LockAwareMessages with relatively small timeout" in {
      val nTimes = 1 to 10
      val now = nowLong()
      val msg = LockAwareMessage(1, () ⇒
        Future {
          val time1 = nowLong() - now
          Thread.sleep(100)
          val time2 = nowLong() - now
          self ! Timespan(1, time1, time2)
        }, 110.millis)

      nTimes.foreach(_ => lockActor ! msg)

      val timespans = nTimes.map(_ => expectMsgType[Timespan]).toList
      println(timespans)
      Timespan.isIntersecting(timespans) should be(false)
    }
```
test doesn't fail every time but if you run it repeatedly you will got an error.
Here is a sample result of failed test:
```List(Timespan(1,32,136), Timespan(1,168,270), Timespan(1,169,273), Timespan(1,272,375), Timespan(1,274,379), Timespan(1,379,482), Timespan(1,380,484), Timespan(1,486,589), Timespan(1,483,587), Timespan(1,591,695))```
As you can see the processes Timespan(1,168,270), Timespan(1,169,273) have Intersection

**Comment by ExNexu** [comment]
It was never meant to be a timeout, but an automatic **expiration** of the lock itself - even if the process was still running.

However, I agree that this is confusing and after some thought I have decided to remove this 'feature' as it is more of an anti-feature. After all the whole lib is about making sure that processes don't run in parallel. (I still left in the manual unlock though)

I have just released the new version `0.0.6` without lock expiration and upgraded akka to 2.5.

I don't know what your exact use-case is, but most likely you want to throw an exception in your code instead, which will halt the process and release the lock.

Thank you for bringing up this issue.

**Comment by mmostovnikov** [comment]
Here is one more test to break message order
```
    "Bad order of messages " in {
      val probe1 = TestProbe()
      val probe2 = TestProbe()
      val ddosProbs: Array[TestProbe] = Array.fill[TestProbe](20)(TestProbe())

      val request1 = () ⇒ Future { Thread.sleep(1000); "OK1" }
      val request2 = () ⇒ Future { Thread.sleep(1000); "OK2" }

      probe1.send(lockActor, LockAwareRequest(1, request1))
      probe2.send(lockActor, LockAwareRequest(1, request2))
      Thread.sleep(990)

      ddosProbs.zipWithIndex.foreach{
        case(prob, index) => {
          Thread.sleep(1)
          val request = () ⇒ Future { Thread.sleep(1); "Extra:OK" + index}
          prob.send(lockActor, LockAwareRequest(1, request))
        }
      }

      probe1.expectMsg("OK1")
      probe2.expectMsg("OK2")
      ddosProbs.zipWithIndex.foreach{
        case(prob, index) => prob.expectMsg("Extra:OK" + index)
      }
    }
```
I reproduced it every time on my machine. Actually the idea is we try to execute one of the extra request early then Request #2 (and Request #2 will be added at the end of queue). To achieve this I start sending new message before request #1 will be finished as result instead of Lock by request #2 we will have Lock by one of the request from ddosProbs.

**Comment by ExNexu** [comment]
I have added your test and fixed the bug causing the sequencing error in version `0.0.7`.

If it does not work, please let me know your machine specs. On the machines I have tried (Two different laptops, one ec2 instance with 8 cores), I was not able to consistently reproduce the bug.

**Comment by mmostovnikov** [comment]
This fix works! Thank you!
