### ISSUE TITLE
The description about order of execution

### ISSUE THREAD

**Issue by okapies** [ExNexu/akka-actor-locking#2]
[README](https://github.com/ExNexu/akka-actor-locking/blob/9c141162135968368338473f7de7ce349c343d9e/README.md) states that:

```scala
lockActor ! LockAwareMessage(lock1, action1) // order is guaranteed
lockActor ! LockAwareMessage(lock1, action2) // runs right after action1 :-)
```

but I think this is depend on the order of arrival of `LockAwareMessage`.

**Comment by ExNexu** [comment]
You're absolutely right. I've cleaned it up. Thank you, Yuta!

**Comment by okapies** [comment]
Thanks!
